# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn dependency:go-offline
      # run tests!
      - run: mvn package
      - run:
          command: mkdir -p test/module1 && cp module1/target/surefire-reports/TEST-io.jitpack.AppTest.xml test/module1 && mkdir -p test/module2 && cp module2/target/surefire-reports/TEST-io.jitpack.AppTest.xml test/module2
          when: on_fail
      - run: 
      - store_test_results:
          path: test
